const express = require('express')
const router = express.Router()
const authRoute = require('./authRoute')
const deviceRoute = require('./deviceRoute')
const rentalRoute = require('./rentalRoute')
const expenseRoute = require('./expenseRoute')
const customerRoute = require('./customerRoute')
const modelRoute = require('./modelRoute')
const supplierRoute = require('./MANAGER_SELL/supplierRoute')
const categoriesRoute = require('./MANAGER_SELL/categoriesRoute')
const goodsReceiptRoute = require('./MANAGER_SELL/goodsReceiptRoute')
const ordersRoute = require('./MANAGER_SELL/orderRoute')
const productItemsRoute = require('./MANAGER_SELL/productItemRoute')

router.use('/auth', authRoute)
router.use('/device', deviceRoute)
router.use('/rental', rentalRoute)
router.use('/expense', expenseRoute)
router.use('/customers', customerRoute)
router.use('/models', modelRoute)
router.use('/sell/suppliers', supplierRoute)
router.use('/sell/categories', categoriesRoute)
router.use('/sell/goodsReceipt', goodsReceiptRoute)
router.use('/sell/orders', ordersRoute)
router.use('/sell/productItems', productItemsRoute)

module.exports = router